"""Native source-build smoke, using disposable data and the actual MCP/Hook entrypoints."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import sqlite3
from contextlib import closing
import subprocess
import tempfile
from test_project_adapter import Client, ROOT

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--runtime',required=True);args=parser.parse_args()
    original=Path(args.runtime).resolve()
    scratch=ROOT/'build';scratch.mkdir(exist_ok=True)
    temporary=Path(tempfile.mkdtemp(prefix='learning-runtime-',dir=scratch))
    payload=temporary/'app/versions/verified-learning';payload.mkdir(parents=True)
    core=payload/'semantic-memory-mcp.exe';shutil.copy2(original,core)
    data=temporary/'data';data.mkdir();workspace=temporary/'workspace';workspace.mkdir()
    os.environ['CBM_VERIFIED_LEARNING']='1'
    client=Client(core,data,command=[str(core)])
    try:
        names=[tool['name'] for tool in client.tools]
        assert 'memory_learning_status' in names and 'memory_learning_control' in names,names
        begin={'project':str(workspace),'workspace':str(workspace),'scope':'project','session_id':'learning-native-session',
            'turn_id':'learning-native-turn','prompt_sha256':hashlib.sha256(b'native learning').hexdigest(),
            'prompt_length':15,'idempotency_key':'learning-native-begin'}
        result,task=client.tool('memory_task_begin',begin);assert not result.get('isError'),task
        result,status=client.tool('memory_learning_status',{'project':str(workspace)})
        assert not result.get('isError') and status['enabled'],status
        hook={'hook_event_name':'PostToolUse','session_id':begin['session_id'],'turn_id':begin['turn_id'],
            'tool_name':'functions.exec_command','tool_use_id':'learning-real-process-result','tool_input':{'cmd':'python --version'}}
        actual=subprocess.run(['python','--version'],capture_output=True,text=True,check=True)
        hook['tool_response']={'exit_code':actual.returncode,'output':actual.stdout,'wall_time_seconds':0}
        env=os.environ.copy();env.update(CBM_DATA_ROOT=str(data),CBM_CACHE_DIR=str(data),CBM_MEMORY_EMBED_BACKEND='static',CBM_MEMORY_AUTO_MAINTAIN='0')
        completed=subprocess.run([str(core),'memory-post-tool'],input=json.dumps(hook),capture_output=True,text=True,encoding='utf-8',env=env,timeout=15)
        assert completed.returncode==0 and 'degraded' not in completed.stdout,(completed.returncode,completed.stdout,completed.stderr)
        result,task_status=client.tool('memory_task_status',{'project':str(workspace),'task_id':task['task_id']})
        assert not result.get('isError') and 'external_verified' in json.dumps(task_status),task_status
        # Seed through the MCP event contract, recall through the real Hook, link the
        # actual process result, and then measure subsequent MCP ranking changes.
        ids=[]
        for label in ('alpha','beta'):
            result,event=client.tool('events',{'project':str(workspace),'scope':'global','kind':'lesson','importance':.72,
                'summary':'Verified learning fixture repair '+label,'content':'Use verified learning fixture repair '+label+' process checks.',
                'source':'isolated-native-test','payload':{}})
            assert not result.get('isError'),event
            ids.append(event['item_id'])
        result,before=client.tool('memories_retrieve',{'project':str(workspace),'query':'Verified learning fixture repair','limit':10,'request_id':'before-learning'})
        assert not result.get('isError'),before
        before_items=before.get('items',before.get('memories',[]))
        assert any(entry['id']==ids[1] for entry in before_items),before
        recall={'hook_event_name':'UserPromptSubmit','session_id':'real-recall-session','turn_id':'real-recall-turn',
            'cwd':str(workspace),'prompt':'Verified learning fixture repair'}
        recalled=subprocess.run([str(core),'memory-recall'],input=json.dumps(recall),capture_output=True,text=True,encoding='utf-8',env=env,timeout=15)
        assert recalled.returncode==0 and 'degraded' not in recalled.stdout,recalled.stdout
        result,recalled_task=client.tool('memory_task_status',{'project':str(workspace),'session_id':recall['session_id'],'turn_id':recall['turn_id']})
        assert not result.get('isError'),recalled_task
        hook.update(session_id=recall['session_id'],turn_id=recall['turn_id'],tool_use_id='real-recall-process')
        completed=subprocess.run([str(core),'memory-post-tool'],input=json.dumps(hook),capture_output=True,text=True,encoding='utf-8',env=env,timeout=15)
        assert completed.returncode==0 and 'degraded' not in completed.stdout,completed.stdout
        result,linked=client.tool('memory_task_status',{'project':str(workspace),'task_id':recalled_task['task_id']})
        # Read-only inspection supplies the exact evidence identity generated by the Hook.
        with closing(sqlite3.connect((data/'__global__-memory.db').as_uri()+'?mode=ro',uri=True)) as db:
            evidence_id=db.execute('SELECT evidence_id FROM memory_evidence WHERE task_id=? AND trust_class=?',
                (recalled_task['task_id'],'external_verified')).fetchone()[0]
        result,finished=client.tool('memory_task_complete',{'project':str(workspace),'task_id':recalled_task['task_id'],
            'outcome':'completed','idempotency_key':'verified-native-complete',
            'attributions':[{'memory_item_id':ids[1],'state':'used','evidence_id':evidence_id}]})
        assert not result.get('isError'),finished
        result,learned=client.tool('memory_learning_status',{'project':str(workspace)})
        learned_item=next(entry for entry in learned['items'] if entry['item_id']==ids[1])
        assert learned_item['positive']==1 and learned_item['utility']>0,learned
        result,after=client.tool('memories_retrieve',{'project':str(workspace),'query':'Verified learning fixture repair','limit':10,'request_id':'after-learning'})
        after_items=after.get('items',after.get('memories',[]))
        original_score=next(entry['retrieval_score'] for entry in before_items if entry['id']==ids[1])
        new_score=next(entry['retrieval_score'] for entry in after_items if entry['id']==ids[1])
        assert new_score>original_score,(original_score,new_score,after)
        result,bad=client.tool('memory_learning_status',{'project':'unknown-other-project'})
        assert result.get('isError') and bad['code']=='SECURITY_SCOPE_VIOLATION',bad
        result,paused=client.tool('memory_learning_control',{'project':str(workspace),'action':'pause','expected_generation':status['generation'],'idempotency_key':'learning-native-pause'})
        assert not result.get('isError') and not paused['enabled'],paused
        result,resumed=client.tool('memory_learning_control',{'project':str(workspace),'action':'resume','expected_generation':paused['generation'],'idempotency_key':'learning-native-resume'})
        assert not result.get('isError') and resumed['enabled'],resumed
        output={'schema':'verified-learning-native-evidence/v1','runtime_sha256':hashlib.sha256(original.read_bytes()).hexdigest(),
            'tool_count':len(names),'real_process_hook_evidence':True,'scope_guard':True,'pause_resume':True,'synthetic_data':True,
            'live_codex_upgraded':False,'ranking_before':original_score,'ranking_after':new_score,'verified_credit':learned_item['positive']}
        (scratch/'learning-runtime-evidence.json').write_text(json.dumps(output,indent=2),encoding='utf-8')
        print(json.dumps(output))
    finally:client.close()

if __name__=='__main__':main()
